### PR TITLE
Add .gitattributes

### PR DESCRIPTION
**Pull request by TangRufus**
Export only `src/*`, `composer.json` and `composer.lock`.
It help reduce package size when install or update with the `--perfer-dist` flag.

### CODE REVIEW

**Comment by jamesryanbell** [comment]
Hi

Can you bump the version number to 1.10.2 please and I will get this merged.

Thanks,
James

**Comment by TangRufus** [comment]
Version bump 1.10.2

**Comment by TangRufus** [comment]
Make travis tests pass and rebased

**Comment by jamesryanbell** [comment]
Thanks

**Pull request merged**
